// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSClear

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> frontSurface;
float4 iClearColor;

[numthreads(32,32,1)]
void CSClear (uint3 id : SV_DispatchThreadID)
{
	// TODO: insert actual code here!

	//frontSurface[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
	frontSurface[id.xy] = iClearColor;
}
